### PR TITLE
Enable kwargs forward dash

### PR DESCRIPTION
**Pull request by sdementen**
added the forwarding of any extra argument given to a DjangoDash (kwargs) to the WrappedDash instance.
this allows to use the external_scripts and external_stylesheets (test added for that)
the other options have not been tested => in the future, it could be better to selectively and explicitly add the arguments to DjangoDash that can be forwarded to the WrappedDash (instead of accepting a **kwargs).

this could fix issue #296 and #226

### CODE REVIEW

**Comment by GibbsConsulting** [comment]
The reason that the code doesn't currently do this is to avoid issues along the lines of 'X doesnt work' where X is some feature of Dash that is not supported by `django-plotly-dash`. However, the current approach of directly naming the supported arguments is somewhat inefficient.

The package is more mature now, so I don't know how many arguments remain in this category, but depending on their number perhaps an explicit list of permitted or unhandled arguments could be used to check against the `kwargs` content.

**Comment by sdementen** [comment]
Currently the code accepts a kwargs but does nothing with it (which can be misleading as the user could expect the kwargs to be handled).
The PR forward the kwargs to Dash which may or may not work (which can also be misleading as some features may be specific to Flask and irrelevant for dpd), if the argument does not exist,  Dash will raise an error.

Both are not great situations.
IMHO, the best would be to explicitly declare the Dash accepted arguments in DjangoDash (To also get autocompletion in IDE) and handle them properly (a) forward to Dash, b) handle in dpd if relevant, c) raise some dpd not implemented error).
What do you think?

**Comment by GibbsConsulting** [comment]
Yes, I think explicitly handling them would be good.

**Comment by sdementen** [comment]
I have added for now the explicit handling of external_stylesheets/external_scripts and added a warning when someone passes extra arguments (ie in the kwargs) not handled explicitly by dpd.
For instance, if a user adds a "compress=True" to its DjangoDash(...) call he/she will see
`UserWarning: You are passing extra arguments {'compress': True} that will be passed to Dash(...) but may not be properly handled by django-plotly-dash.`

**Pull request merged**
