### PR TITLE
Add support for Django 4.x. Closes #403

### LINKED ISSUE #403: Enable use of Django 4.0 and higher
Changes in Django for major version 4 need to be accommodated in Dash. This is a placeholder for this work.

### PR DESCRIPTION
**Pull request by radusuciu**
Changes are as follows
- updated `requirements.txt` and `setup.py` to allow for Django 4.x installs
- add missing dependencies to demo application (and freeze requirements)
- remove import of deprecated (and unused) url function in the demo
- upgrade demo to use `channels` 4.0
- remove deprecated `USE_L10N` setting in demo
- set default auto field in `AppConfig` (fixes models.W042 warning)

Demo seems to work well and all tests pass. Please test before merging. Happy to make other changes as requested.

### CODE REVIEW

**Comment by radusuciu** [comment]
@delsim does this pass the smell test for what you think would be necessary for the 4.0 upgrade? Most of the changes I made were for the demo app than the actual core library.

**Comment by delsim** [comment]
@radusuciu yes I think it looks good from a quick scan. Unfortunately not had the cycles yet to read in-depth or try it out.

**Comment by varunm22** [comment]
Is there an estimated time on when this may be reviewed and merged? This would be very useful for me, as we want to upgrade django-plotly-dash to use dash 2, but don't want to downgrade our mesa version.

**Comment by delsim** [comment]
@radusuciu thanks for this, much appreciated, and finally got some time to look at this.

There's something we need to address - the changes to routing.py need to ensure that the current routes are all supported and also to make sure the file is backwards compatible for existing users.

**Comment by delsim** [comment]
I adapted your changes (my github skills are not up to building on top of another pull request, unfortunately) and merged them as #455
However, the demo remains to be fixed.

**Comment by radusuciu** [comment]
Thanks for incorporating the changes! I can test this on internal application I maintain that uses dpd.

I can take a crack on fixing more obvious issues (if they exist.. eg. dependency conflicts, warnings etc.) if you'd like

**Pull request closed without merging**
