### PR TITLE
support pattern matching

### LINKED ISSUE #264: Add support for wildcard callbacks
Dash now permits the use of wildcards in callbacks. This issue is a placeholder for investigating the work needed to extend support to cover this feature and for any resultant implementation.

If you are interested in sponsoring this work please reach out [here](https://gibbsconsulting.ca/).

### PR DESCRIPTION
**Pull request by sdementen**
first attempt at supporting pattern matching (fix #264 and #277)

support for:
- initial_arguments
- dispatch by dpd

todo:
- [ ] write tests
- [ ] see if works with "save_on_change" (but could not find any app to test this)

### CODE REVIEW

**Review by GibbsConsulting — APPROVED** [review]

**Comment by sdementen** [comment]
There is still the save state in database part that should be adapted but I am not sure there is a test already written that test the base functionality (before even looking at IDs with patterns)

**Comment by radupm** [comment]
@sdementen First of all, thanks for your contribution, as well a big up to @GibbsConsulting for the library!

I waited eagerly for the PMC's to be available in dpd and tried it out. At first I thought I did something wrong as I got an error, but than I tested the app provided by dash as an example in their [docs (Simple example with ALL)](https://dash.plotly.com/pattern-matching-callbacks). I get the same error.

```
Traceback (most recent call last):
  File "./venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "./venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "./venv/lib/python3.8/site-packages/django_plotly_dash/views.py", line 74, in update
    return _update(request, ident, stateless, **kwargs)
  File "./venv/lib/python3.8/site-packages/django_plotly_dash/views.py", line 91, in _update
    resp = app.dispatch_with_args(request_body, arg_map)
  File "./venv/lib/python3.8/site-packages/django_plotly_dash/dash_wrapper.py", line 710, in dispatch_with_args
    if c["property"] == component_registration["property"] and compare(
TypeError: list indices must be integers or slices, not str
```
Versions:
```
Python 3.8.6

Django==3.1
django-plotly-dash==1.6.0
dash==1.19.0
dash-core-components==1.15.0
dash-renderer==1.9.0
```

What am I missing?

**Comment by sdementen** [comment]
@radupm could you try the branch in #316 ?
The pattern support from this PR was not finished. The one in #316 has been tested more thoroughly.

**Comment by radupm** [comment]
@sdementen That one seems to work. I'll wait for the merge, which, I assume, will result in a new version which will cover the fixes

Thanks again!

**Comment by sdementen** [comment]
@radupm feel free to test this branch on real dash apps with patterns. It seems to me it is pretty well tested but always good to have a real beta tester

**Comment by radupm** [comment]
@sdementen I tested the branch with a complex app _(dynamically generated components, patterns for Input, State and multi Output, both with ALL and MATCH)_ for which I was planning to refactor with PMC's and it work just right. No issues whatsoever :rocket:  ! Wating for #316 to be approved!

Great stuff :1st_place_medal: ! Thanks again!

**Comment by sdementen** [comment]
nice!
did you also use the "state" saving (ie with a stateful app that saves the changes in the dash client in the DB) ?

**Comment by radupm** [comment]
I am not sure about the state saving. The only state I use with dpd is getting the request from the views to the dash app via session_state. I feel like I am missing out on some features? :thinking:

**Pull request merged**
