### PR TITLE
fix template tag name

### PR DESCRIPTION
**Pull request by weber-s**
A simple "fixing typo" PR.

Thanks for your job :+1:

### CODE REVIEW

**Comment by GibbsConsulting** [comment]
Thanks for the contribution. However, isn't the documentation correct when it says that the tag is called ``plotly_app`` ?

**Comment by weber-s** [comment]
Oh. Sorry. indeed. That `plotly_item` that does not exist. I was confused because the docs in ["Simple usage"](https://django-plotly-dash.readthedocs.io/en/latest/simple_use.html) as well as in ["template tag"](https://django-plotly-dash.readthedocs.io/en/latest/template_tags.html) is the following:

```
.. code-block:: jinja

  {%load plotly_dash%}
  {%plotly_item name="SimpleExample"%}
```

Then, this example is wrong. 
There is a bunch of example with `plotly_item`, should it be corrected to `plotly_app` ?

```sh
>>> git grep plotly_item
README.md:{% plotly_item name="SimpleExample" %}
django_plotly_dash/templatetags/plotly_dash.py:@register.inclusion_tag("django_plotly_dash/plotly_item.html", takes_context=True)
docs/installation.rst:The ``plotly_item`` tag in the ``plotly_dash`` tag library can then be used to render any registered dash component. See :ref:`simple_use` for a simple example.
docs/simple_use.rst:  {%plotly_item name="SimpleExample"%}
docs/template_tags.rst:  {%plotly_item name="SimpleExample"%}
docs/template_tags.rst:  {%plotly_item ... DjangoDash instances using live updating ... %}
```

**Comment by GibbsConsulting** [comment]
Yes, it looks like the documentation didn't get updated when the code was refactored.
Are you in a position to submit an updated pull request? No worries if not.

**Comment by weber-s** [comment]
Hi!

Here is a commit to fix this issue.

**Comment by GibbsConsulting** [comment]
Merged into prerelease branch v0.5.1. Thanks very much for the contribution.

**Pull request merged**
